fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Vusalba\UserBundle\Entity\User
    from_email:
        address: ibrahima-sory.diallo@albasoft.fr
        sender_name: albasoft-team
