vue_axe_groupe:
    resource: "@VueBundle/Controller/AxeGroupeController.php"
    type:     annotation

vue_groupe:
    resource: "@VueBundle/Controller/GroupeController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

vue_level:
    resource: "@VueBundle/Controller/LevelController.php"
    type:     annotation


vue_node:
    resource: "@VueBundle/Controller/NodeController.php"
    type:     annotation

vue_axis:
    resource: "@VueBundle/Controller/AxisController.php"
    type:     annotation

vue_composant:
    resource: "@VueBundle/Controller/ComposantController.php"
    type:     annotation
vue_analyze:
    resource: "@VueBundle/Controller/analyzeController.php"
    type:     annotation
vue_admin:
    resource: "@VueBundle/Controller/AdminController.php"
    type:     annotation
vue_enterdata:
    resource: "@VueBundle/Controller/EnterDataController.php"
    type:     annotation
vue_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
vue:
    resource: "@VueBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#User bundle routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
