security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_GESTIONNAIRE:    ROLE_USER
        ROLE_ADMIN:    ROLE_GESTIONNAIRE
        ROLE_SUPER_ADMIN:    ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: redirect.after.login
                always_use_default_target_path: false
                default_target_path:            /enterData/
                target_path_parameter:          _target_path
                use_referer:                    false
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/enterData, role: ROLE_GESTIONNAIRE }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN   }
        - { path: ^/administration/, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN }