<?php

namespace Vusalba\VueBundle\Repository;

/**
 * AxeGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxeGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
