<?php

namespace Vusalba\VueBundle\Repository;

/**
 * AxisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxisRepository extends \Doctrine\ORM\EntityRepository
{
}
