<?php

namespace Vusalba\VueBundle\Repository;

/**
 * entityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
